### ISSUE TITLE
Offer a "Custom List" toggle for following specific shows regardless of airing/follow status

### ISSUE THREAD

**Issue by starg09** [TehNut/AniMouto#10]
If users toggle it on, instead of showing the anime in "Airing" and "In Progress" automatically based on AL, the extension will list all entries in a custom list (named "Animouto"?) where one can be more specific and always see the shows they want (even those not yet airing, as a reminder to start them once they air in case notification doesn't popup or is ignored).

**Comment by TehNut** [comment]
Current status

![](https://giant.gfycat.com/CreamySaltyAnnelida.gif)

To copy commit description:

> Currently the ability to switch between "Default" and "Starred" lists exists, however there is no way to star a media, nor does it account for media that don't meet the requirements for the default list.
