### ISSUE TITLE
Rate anime/manga after making last episode/chapter as watched/read

### ISSUE THREAD

**Issue by Closet0taku** [TehNut/AniMouto#12]
I want to be able to rate anime within the extension after finishing something instead if having to go to AniList and logging in every time and finding the anime to rate it. Currently I usually just go to an app on my phone I use since it'll let me rate it after i mark the last episode/chapter as finished.

**Comment by TehNut** [comment]
Smilies (yeah, yeah, yeah, the buttons have weird extra space on the side)

![image](https://user-images.githubusercontent.com/5789439/67357491-3e014d80-f512-11e9-9d11-3340027dc39f.png)

**Comment by Closet0taku** [comment]
Aye those looks nice though! I don’t really use smilies but I might seeing this

**Comment by TehNut** [comment]
And finally stars

![image](https://user-images.githubusercontent.com/5789439/67359402-ff6e9180-f517-11e9-867e-2a9ffc533fdd.png)

>Aye those looks nice though! I don’t really use smilies but I might seeing this

Thanks! I just want to make sure I support every rating type otherwise people will yell at me :^)

**Comment by Closet0taku** [comment]
> Thanks! I just want to make sure I support every rating type otherwise people will yell at me :^)

I don’t blame you haha but honestly this alone was the only feature I felt was missing. It always got me a little mad when I forget that I couldn’t rate anything after marking it done and I would have to do extra steps just to rate something. Or option B was to get my phone and open up an app to rate it even though I was already on my laptop. Thanks a bunch!
