### ISSUE TITLE
Add the color "pink" to the list of colors available to customize the look.

### ISSUE THREAD

**Issue by Closet0taku** [TehNut/AniMouto#15]
I really like the pink color scheme on AniList but I don't see an option for a Pink color scheme with this extension. The one that looks like pink is more of an orange-red or orange-pink color. I was wondering about just pink as a color scheme option.

**Comment by TehNut** [comment]
Huh, I thought I had done all the same colors.

**Comment by Closet0taku** [comment]
> Huh, I thought I had done all the same colors. Will get this done for the next update.

![Maybe it's me but they look like two different colors. Thanks though!](https://user-images.githubusercontent.com/20650049/69591239-bba7f580-0fb7-11ea-901e-a5e846980da7.JPG)

Also. color picker like donors would be pretty awesome!

**Comment by TehNut** [comment]
![image](https://user-images.githubusercontent.com/5789439/69593773-14bf5b80-0faf-11ea-8641-5a7078916397.png)
