### ISSUE TITLE
Can't login to AniList on Firefox

### ISSUE THREAD

**Issue by biehlerj** [TehNut/AniMouto#16]
When trying to login to AniList using the Firefox extension the page the app tries to redirect to after logging in and authorizing the app says it doesn't exist. Because the extension can't find the server it needs to talk to logging in is broken. The issue is occurring on my machine running Firefox version 70.0.1 Mozilla Firefox for Ubuntu on Pop!_OS 19.10. 
![Screenshot from 2019-12-07 22-00-28](https://user-images.githubusercontent.com/22229994/70384963-1f79d900-193d-11ea-888b-7731d8b75c7f.png)

**Comment by TehNut** [comment]
Strange, my Firefox detection should be using a different client code than the Chrome auth.

**Comment by TehNut** [comment]
Interesting difference in results for where my check is done.

**Comment by TehNut** [comment]
Should be live momentarily.

**Comment by biehlerj** [comment]
Wow, that was fast! It was interesting looking at your changes and stepping through your codebase to learn a little bit about Vue.

**Comment by TehNut** [comment]
I wouldn't take this project as a "this is how you should use Vue!" example. This is my first foray into using it and I'm sure I do *many* things in a, well, less than ideal way.

>Thanks for the quick turn around!

No problem, it was a quick fix. Took longer to draft the release than to fix the problem
