### ISSUE TITLE
can't find my list

### ISSUE THREAD

**Issue by Karechta** [TehNut/AniMouto#18]
I have this issue since a few days, where animouto cant find my Anilist. It doesnt show my current progress of watching and airing anime, instead a red message "I tried my best but couldn't find your list".
The rest of the features seem to work.

**Comment by Karechta** [comment]
Bananya was the issue

**Comment by TehNut** [comment]
Duplicate of [this comment tree](https://anilist.co/forum/thread/7424/comment/226935) but now it's here so I can remember it exists 👍

**Comment by TehNut** [comment]
Fixed in 2.0.14 which should be live soon
