### ISSUE TITLE
Is it supposed to mark the date completed?

### ISSUE THREAD

**Issue by IJustDrankALavaLamp** [TehNut/AniMouto#22]
every time I finish a show I have to go onto anilist and mark the date it was completed

**Comment by TehNut** [comment]
It is supposed to, and [*should*](https://github.com/TehNut/AniMouto/blob/master/src/popup/components/medialist/MediaCard.vue#L105-L108). I'll take a look when I get a chance.

**Comment by TehNut** [comment]
I was checking completion against the progress prior to the update which *obviously* never returned true. Oopsy
