### ISSUE TITLE
[Suggestion] Is it possible to make the detailed view the default?

### ISSUE THREAD

**Issue by Invisible40** [TehNut/AniMouto#23]
Whenever I search for anime, I see the search listings, but clicking the name of the anime (or the white space) takes me to the AniList website. On the other end, clicking the three dots takes me to the detailed view.

Would it be possible to switch this around, or at least give an option to do so? I love the extension, but I normally just use it for searching anime titles, and I'd like to stay inside the extension if possible as opposed to going to another website.

Thanks!

**Comment by TehNut** [comment]
Yeah that makes sense. Clicking the name should stay within the window and I can swap the dots for an outgoing link icon.

**Comment by Invisible40** [comment]
Yeah or you can make it an option in the settings. Either way, thanks for responding!
