### ISSUE TITLE
Logs out everytime I use close chrome!

### ISSUE THREAD

**Issue by rsmyst** [TehNut/AniMouto#28]
Just as the title says. **Every time I close chrome and reopen, it logs out of my anilist account**. I am using the latest version of chrome and windows and animouto. 
BTW, this issue started only about a week ago. Please fix :)

**Comment by TehNut** [comment]
Shit

**Comment by TehNut** [comment]
Does not seem fixed. Very confused.

**Comment by FurySkore** [comment]
> Just as the title says. **Every time I close chrome and reopen, it logs out of my anilist account**. I am using the latest version of chrome and windows and animouto.
> BTW, this issue started only about a week ago. Please fix :)

btw i'm on brave who use chromium and everyday i have to reconnect my account because i'm log out, so it's the same issue

**Comment by StefanPuia** [comment]
not sure if related, but the login popup is not opening at all now:
![image](https://user-images.githubusercontent.com/24592655/89945379-346be200-dc19-11ea-8a63-c0576545a76a.png)

**Comment by TehNut** [comment]
It's somehow getting worse! 🎉

**Comment by TehNut** [comment]
I'm not able to reproduce the auth page error, but could you check the version currently installed?

**Comment by StefanPuia** [comment]
ok so after some testing, it seems the authorisation page was not launching when I had a proxy on.
the authorisation itself seems fine now, session remains after relaunching the browser

**Comment by TehNut** [comment]
Hm. I'll leave this open for now because I still experience the logout myself but haven't been able to reproduce it. Added some very aggressive logging so hopefully I can catch it next time.

**Comment by TehNut** [comment]
Aha, my understanding of how `fetch` handles errors was flawed.

![image](https://user-images.githubusercontent.com/5789439/90072582-8f024e00-dcac-11ea-8701-232556f2763b.png)

**Comment by Invisible40** [comment]
I was getting this issue for a few days too, but I think it stopped yesterday.

**Comment by TehNut** [comment]
I left this open just in case, but I'm fairly confident the latest build fixed the issue

**Comment by TehNut** [comment]
I don't care anymore, I'm reverting the expired token checks.

**Comment by SkySCC** [comment]
Looks like it has been fixed... AWESOME. it doesn't log out randomly anymore.

**Comment by TehNut** [comment]
It does on Firefox 
![](https://cdn.discordapp.com/emojis/586283629014024238.png?v=1)

**Comment by TehNut** [comment]
Ok, I'll give it one last shot. In the update I'm about to push, additional debug has been added. If you are logged out by the check, the errors involved will be stored. If any errors are stored, a new button in the top part of the settings page will appear.
![image](https://user-images.githubusercontent.com/5789439/93652171-f8226300-f9c8-11ea-852e-a314443b474c.png)
Clicking this button will copy all errors to your clipboard so you can share them with me here. Hopefully this will help me find whatever smooth brain code I wrote that caused all of this 😤

**Comment by Leojnv** [comment]
Hi, I'm having similar problems in Edge Chromium but it's not every time I close the browser, it's at random times.
Sometimes it happens every few minutes, others it happens with days of difference.
Here's the logout debug:
[
  {
    "error": [
      {
        "locations": [
          {
            "column": 2,
            "line": 1
          }
        ],
        "message": "Invalid token",
        "status": 400
      }
    ],
    "time": 1600817190003
  }
]

**Comment by jaideepheer** [comment]
Hi, any fixes for this?
I've been experiencing this bug for a while now.

**Comment by TehNut** [comment]
Disable it in settings. A proper fix will come in 3.0 
https://github.com/TehNut/AniMouto/projects/2#card-51133391

**Comment by TehNut** [comment]
This should actually definitely probably not be an issue in the new rewrite.
