### ISSUE TITLE
No desktop notifications

### ISSUE THREAD

**Issue by DETahaX** [TehNut/AniMouto#31]
I have turned on the setting in the extension to gain desktop chrome notifications for any notification I get on my AniList account. But it does not work, I have gotten notifications on the site, yet I get no pop-up what so ever from chrome about it. Can I please contact someone about this to help?

**Comment by TehNut** [comment]
I did notice this myself, but when I looked into it at the time, I couldn't figure out what changed. I put it on my backburner hoping nobody would report it :^)

I'll take another look

**Comment by TehNut** [comment]
Ok looking into it more, it seems that at *some point*, notifications were changed to [not allow urls to images for notification icons](https://developer.chrome.com/extensions/notifications#property-NotificationOptions-iconUrl). This *used* to work, but now it doesn't 🤷 

I'll try converting them to blob urls locally and see if that can get around it

**Comment by TehNut** [comment]
Due to CORS issues, I can't display user avatars or media covers in notifications anymore. The AniMouto logo will now be displayed in it's place.

![image](https://user-images.githubusercontent.com/5789439/93651580-d627e100-f9c6-11ea-8fbf-1ddca7585cb7.png)
