### ISSUE TITLE
Card profile badge render issue

### ISSUE THREAD

**Issue by TeamDman** [TehNut/AniMouto#32]
Looks like the badge image is having some issues.
[https://card.animouto.moe/badge/TeamDman](https://card.animouto.moe/badge/TeamDman)
![https://card.animouto.moe/badge/TeamDman](https://card.animouto.moe/badge/TeamDman)
![image](https://user-images.githubusercontent.com/9356891/98888449-0b502d00-2466-11eb-8f45-1f0795ad8ce1.png)

**Comment by TehNut** [comment]
That's not this project smh baka
