### ISSUE TITLE
Visual Bug in Widen Mode with > 5 Manga on In Progress

### ISSUE THREAD

**Issue by jjhhgg100123** [TehNut/AniMouto#33]
The title lapses outside of the menu on the first manga of any row save the first. Also the third row last manga goes the wrong way. Weird.
![se3Hc](https://user-images.githubusercontent.com/7052039/100324704-84e82f00-2fbf-11eb-9da5-2d1fc0b02391.png)

It's fine without widen mode on.

Browser: Firefox Dev 84.0b4 (64-bit), latest extension.

**Comment by TehNut** [comment]
Hm, this usually only happens after completing something and causing the whole list to shift. I have since rewritten the logic for determining which side the popover should appear on, but it hasn't made it's way into a release yet.
