### ISSUE TITLE
No insertion or management of status on manga/anime main page

### ISSUE THREAD

**Issue by manzajp** [TehNut/AniMouto#37]
It is possible to put the add to current/planning in the main page of the said anime/manga as well? I find it bizarre to find related anime/manga just to re-search back the name.

**Comment by TehNut** [comment]
This was planned from the start, but I couldn't find a decent way to design it so it was put on the back burner. I plan to have this ready for the 3.0 version.

**Comment by manzajp** [comment]
Ah I see. Thank you for such a good extension either way and all the best.

**Comment by TehNut** [comment]
![image](https://user-images.githubusercontent.com/5789439/200139477-88f6944c-8fd5-4ae3-a256-c0b4b4f37c9d.png)

Down the road the left button will function as a way to do more fine-grained list entry management.
