### ISSUE TITLE
Hovering, the texts are jumbled together

### ISSUE THREAD

**Issue by hotlikewassabi** [TehNut/AniMouto#38]
![image](https://user-images.githubusercontent.com/72563499/110331483-24ef3300-805a-11eb-913d-7031224ffd27.png)

So whenever I hover to the anime or manga, the progress and the "(number) episode behind" is jumbled together. I installed the extension today on microsoft edge which supports chrome extensions.

**Comment by TehNut** [comment]
That title text looks far larger than it's supposed to be. Even so, this is also an issue on AniList itself.

I've already taken care of this in the rewrite, so titles will be truncated at the end of their second line.
