### ISSUE TITLE
Idea Request: Condensing Airing Anime and Anime in Progress Together

### ISSUE THREAD

**Issue by evka745** [TehNut/AniMouto#47]
I feel like a way to condense airing and anime in progress together would be a smart feature to add for people who would prefer it

**Comment by TehNut** [comment]
![image](https://user-images.githubusercontent.com/5789439/200139454-81196634-8d38-4c65-b0d3-1b6000252c29.png)

**Comment by evka745** [comment]
Woahh, that's cool. Is this in the next update?

**Comment by TehNut** [comment]
Yup! It may take a bit to get pushed out, but it's been submitted
