### ISSUE TITLE
Anime list is blank (using new Edge browser with Chrome version of extension)

### ISSUE THREAD

**Issue by ItsCalcifer** [TehNut/AniMouto#48]
![image](https://user-images.githubusercontent.com/78554427/139525542-e4cd4235-327f-4789-849d-896d47a8eb5b.png)

Everything else works but when I click the list button it just loads and nothing happens

**Comment by TehNut** [comment]
Issue was replied to in the forum thread [here](https://anilist.co/forum/thread/7424/comment/1357246).
