### ISSUE TITLE
unknown notification 

### ISSUE THREAD

**Issue by PerfectingBad** [TehNut/AniMouto#49]
While i was on my system i received a notification in my AniMouto extnsion
![123](https://user-images.githubusercontent.com/93696174/140257009-32ee7897-f325-4e2d-ad4d-ab72ef3d825e.PNG)

**Comment by TehNut** [comment]
This is probably one of the [new data change notifications](https://anilist.co/forum/thread/3878/comment/1224532), which I have implemented for the next version (https://github.com/TehNut/AniMouto/commit/6cb5151529195602dc0642720e13da1ff2356fa4). I need to finish bringing that branch to feature parity with the current release before I release it, though.

**Comment by nattadasu** [comment]
Got the notification too. From my end, it's about status change :eyes:
<details><summary>NSFW-ish screenshot</summary><img src="https://user-images.githubusercontent.com/49780229/162043163-f1c39cb4-ee2e-4109-ab5a-9af7212dc9b7.png">
<a href="https://anilist.co/manga/109511/Aein-Shuttle/">Aein Shuttle</a>
</details>

**Comment by ig4e** [comment]
yeah i got it too
![image](https://user-images.githubusercontent.com/50212311/166677234-88ca1c58-2e98-441c-9e8b-5fa96e39a263.png)

**Comment by TehNut** [comment]
I (finally) published the rewrite to both the FF and Chrome webstores. All current notification types should now be supported.
