### ISSUE TITLE
Feature Request: Setting the volume count after finishing a manga

### ISSUE THREAD

**Issue by ereinstein** [TehNut/AniMouto#52]
Animouto apparently already seems to set the finish date on its own after an anime or manga is finished. In a similar vein, it would be quite nice if it would also set the volume count to the volume count stated on the media's page after finishing a manga. Currently, it just leaves it at zero when you finish a manga and you need to manually edit in that information afterwards.

**Comment by TehNut** [comment]
I'm not sure why I never thought to do this before.
