### ISSUE TITLE
Unknown Notification Type

### ISSUE THREAD

**Issue by tnvulcan** [TehNut/AniMouto#53]
Hello. Reporting an unknown notification. 
![Screenshot 2021-11-29 at 21-24-58 Notifications · AniList](https://user-images.githubusercontent.com/78720684/143975558-569e966e-2bf5-47e4-9736-eed4fe689403.png)

**Comment by TehNut** [comment]
Thanks, but this is already reported here. https://github.com/TehNut/AniMouto/issues/49
