### ISSUE TITLE
Can’t connect.

### ISSUE THREAD

**Issue by evka745** [TehNut/AniMouto#55]
<img width="515" alt="Screen Shot 2022-01-09 at 7 01 09 PM" src="https://user-images.githubusercontent.com/82726788/148706536-6f635f5f-df88-443e-9b0d-06b76b3be83d.png">

I have tried resetting my computer, deleting the extension, resetting chrome and none has worked. Any help?

**Comment by TehNut** [comment]
The API has been temporarily disabled.
