### ISSUE TITLE
Animouto not working and showing ip ban on MAL. HELP

### ISSUE THREAD

**Issue by PerfectingBad** [TehNut/AniMouto#56]
I just opend my system, like i always do. I noticed that animouto was not working. I thought may be its an extension problem but some time later i saw that in my MAL (where anilist is master ofcoure) its showing that "Your IP has been banned on ANILIST, change your IP or wait for it to get unbanned"

Please could someone tell me what is happening. Am i in a bad spot. Is my account banned? What about my data?

**Comment by TehNut** [comment]
The API has been temporarily disabled.
