### ISSUE TITLE
switch users

### ISSUE THREAD

**Issue by anoxmoxss** [TehNut/AniMouto#57]
when ever i want to switch accounts i log out then press log in and it takes me back to the same account

**Comment by UpcraftLP** [comment]
you would need to also log out of the anilist homepage / change accounts there, before attempting to log back in.

**Comment by anoxmoxss** [comment]
> f the an

didn't work

**Comment by TehNut** [comment]
This is due to how the oauth library that AL uses remembers the last account you logged into in order to speed up the auth process.
