### ISSUE TITLE
Feature Request : USER NOTES #Enhancement

### ISSUE THREAD

**Issue by hsinankirdar** [TehNut/AniMouto#59]
Suggestion : User notes can also be displayed when hovering over the anime with the mouse. Also, if there is a link, it can be made clickable in the note shown. With this link, we can easily access the service we watch anime.

**Comment by TehNut** [comment]
Where would this be displayed? How would it be displayed? Shown on hover implies a tooltip, which isn't something you interact with with your mouse which means links wouldn't be clickable.

Also, streaming sites like Crunchyroll, Funimation, etc are already shown on the media page.

**Comment by TehNut** [comment]
Closing because there was no follow up.
