### ISSUE TITLE
unknown notification type

### ISSUE THREAD

**Issue by MarioMasta64** [TehNut/AniMouto#67]
<img width="801" alt="Screen Shot 2022-07-01 at 10 49 25 PM" src="https://user-images.githubusercontent.com/20806802/176983965-0eaf3ea8-b4ad-4345-9fe3-207103c6a798.png">

<img width="643" alt="Screen Shot 2022-07-01 at 10 49 49 PM" src="https://user-images.githubusercontent.com/20806802/176983989-bc0da750-3bb1-42e1-a3fa-270c6ded29dd.png">

this happens when an anime is removed

**Comment by MarioMasta64** [comment]
it also seems to trigger a notification misplaced when like removal is turned on but not when its not

**Comment by TehNut** [comment]
#49
