### ISSUE TITLE
Feature request: Crunchyroll seasons fix

### ISSUE THREAD

**Issue by KingCreeperDJ** [TehNut/AniMouto#68]
It would be nice if the extension would take the info from an anime and use it to group the seasons of an anime on crunchyroll in the correct order.

E.g.
### OLD
* season 01 (Spanish dub)
* season 01 (Portuguese dub)
* season 01 (English dub)
* season 02
* season 12 (Spanish dub)
* season 29

### NEW
* season 01
  * Sub
  * Spanish dub
  * Portuguese dub
  * English dub
* season 02
  * Sub
  * Spanish dub
  * Portuguese dub
  * English dub

**Comment by TehNut** [comment]
I'm not sure what you're asking. This extension doesn't have anything to do with Crunchyroll.
