### ISSUE TITLE
Get Code Button and Authorization Code Input missing

### ISSUE THREAD

**Issue by Spimy** [TehNut/AniMouto#70]
My main browser is Firefox Developer Edition but as the Title suggests, the button and input are missing:
![image](https://user-images.githubusercontent.com/34989646/188286160-98ebeda8-c4bb-4647-a711-81b362229d48.png)

It is working perfectly fine on the standard version of Firefox though:
![image](https://user-images.githubusercontent.com/34989646/188286202-1be8d079-2120-46ec-966f-4bd62baa4dde.png)

I cannot login because of this issue.

**Comment by TehNut** [comment]
Mozilla has (for some reason) decided to unhide the `InstallTrigger` type in non-default FireFox browsers for some reason. This is a pretty common way of checking if the environment is FF or Chromium, and how I do it. This check has become unnecessary in the [`rewrite/svelte`](https://github.com/TehNut/AniMouto/tree/rewrite/svelte) branch, but that has not yet been released. 

I do not intend to push out a new build of the 2.0 branch, so you can either go without AM for a bit or use normal FireFox.
