### ISSUE TITLE
Doesn't login with Firefox

### ISSUE THREAD

**Issue by Blueaulo** [TehNut/AniMouto#71]
I just switched from chrome and I installed the app without problem but I can't login and so use the app.
The only thing it does is redirects me in this page: https://ilhjhegbgdghfkdgeahkpikkjgaaoklh.chromiumapp.org/oauth#access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImVlNDNmNGJhOGY4YWQzMWIxMmMyZjg4ZWU5N2NlODUxNzUwZTZhODlmMDlkZTU3Yjc4ZWIzOTMzM2E1NWQxZGRmYzk5NDRkYWQxZmZjYzlmIn0.eyJhdWQiOiIxMzg3IiwianRpIjoiZWU0M2Y0YmE4ZjhhZDMxYjEyYzJmODhlZTk3Y2U4NTE3NTBlNmE4OWYwOWRlNTdiNzhlYjM5MzMzYTU1ZDFkZGZjOTk0NGRhZDFmZmNjOWYiLCJpYXQiOjE2NjQxOTE2NjYsIm5iZiI6MTY2NDE5MTY2NiwiZXhwIjoxNjk1NzI3NjY2LCJzdWIiOiI2MTExNDYiLCJzY29wZXMiOltdfQ.TXK5eJkhBwIV9XVjRXYUaivttqXeSATZFcqkH85aYgRh6nH_K4XNLUOBo3JeNlHu9AHCW5hBfBRvWiEABrpMa0LmcjGWsWLXHGuSvFV0Z6G7SbLByJhAdAijkO4jJJ0vI7lFyE8NiRX4lNBw86oKzdQwZ91RugE5aqlfJDfmKZO8mzixofa8RmrCnr5WegfgnszViNkdIguTqo6yVUWF-b8fBwGIArMKjumNzzPgGBs3NXgYujA2JPS5Gu_Sm9j2b9_hZvJ2y7BV6a59siNGm4IpPyxlOjZbkKLFC2c-Oe0Ak6Ij2avMil1iBkfp_dBq8RrWBI032tiPAJDiUZ29UWxarTpCrfOuPYkeA5JM-EWwJgLewvnMbIwSie3BK_iR-qn49Yr9KNTCvaiawDoNgBJ_JMojVl6YYW2now9qWgC_V-eK-2U7l9s6mbl8UauVq6F5y9sChFC25LnbW6KwhqePAVKcypk9oQx7xGngmxQQWrXSyPLT9y-Kc2cKHMx7laT40EU0R1OqOvD42ixg1XVovYlyDIg_dx2OBaBj_UfuOtoe9AGM4Je_hV_BGsT3WBH7Xv0SHQCn8IKdtgXBBO7F-kNFy4qNvGaKGGMbJ5CsuaDt0T7VpOQmI8Ce9XwJIpzWfSH-qcbgG4IQnijBQc1mFsQsjnkFHWp5p4aaUYg&token_type=Bearer&expires_in=31536000, that my browser can't load

**Comment by Blueaulo** [comment]
https://imgur.com/gallery/tCl69F1
Here is an image

**Comment by TehNut** [comment]
https://github.com/TehNut/AniMouto/issues/70#issuecomment-1236203670

Also, that link contains an access token that allows 3rd parties to act on your behalf. You should never post it publicly.

**Comment by Blueaulo** [comment]
Oh, i understand, thank you very much
