### ISSUE TITLE
Reducing Query Count to avoid rate limits

### ISSUE THREAD

**Issue by LeonVQZ** [TehNut/AniMouto#76]
![image](https://user-images.githubusercontent.com/33768736/202221186-2de6b383-2729-459c-9cb4-afe2a2fa9530.png)

When reaching the query limits the extension becomes unusable unless the query count goes down. Is there a setting I need to change in order to avoid hitting the limit?

**Comment by TehNut** [comment]
#75 

The rate limit you are reaching is on the Cloudflare side and not part of the standard API rate limit. There isn't a way for this to be detected and handled. All third party software for AniList is currently experiencing this and the only solution is to wait until our hardware issues are solved.
