### ISSUE TITLE
Notifications doesn't load

### ISSUE THREAD

**Issue by alyyasser** [TehNut/AniMouto#85]
the notifications feature suddenly not working on me, i only get empty list and "load more" button
![image](https://github.com/TehNut/AniMouto/assets/16476111/b6649877-35ee-419d-be57-310bd7750ff5)

**Comment by UpcraftLP** [comment]
Did your token expire?

Try refreshing it.

**Comment by alyyasser** [comment]
tried that. logout, revoke token, then login again, still have the same problem

**Comment by alyyasser** [comment]
other features works fine

**Comment by alyyasser** [comment]
i tried inspect popup, here's what i get in console log:
![image](https://github.com/TehNut/AniMouto/assets/16476111/98d998ad-b8c0-4a76-a5e5-bafed3dd0363)

**Comment by TehNut** [comment]
What types of notifications have you gotten recently?

**Comment by alyyasser** [comment]
new episode aired notifications.

**Comment by alyyasser** [comment]
i'll be closing this issue because it working again when i checked it today. idk what changed, im just glad it get fixed.

**Comment by TehNut** [comment]
It's probably just that the notification causing the problem got pushed to the next page. The problem is still there, just hidden now

**Comment by Sodj** [comment]
This exact issue is happening to me after receiving a notification from a forum thread (Episode discussion)
I expect the issue to be gone once the thread notification is in second page but this should be resolved because when this happens i can't even go to listing or any other tab

@alyyasser please re-open this so it can be addressed

**Comment by TehNut** [comment]
I am not actively working on this project right now. My time is being spent on AniList itself.

**Comment by Sodj** [comment]
@TehNut understandable, if there are any job openings ping me
